version: "3"

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    restart: always
    
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5431:5432"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}

  redis:
    container_name: redis
    image: 'redis:6'
    ports:
      - "6661:6379"
    restart: always
    
